### ISSUE TITLE
Support for !important @extend

### ISSUE THREAD

**Issue by minimit** [csstools/postcss-extend-rule#12]
Is it possible to support !important in extend compiled? I know the @extend specifications don't specify it..

```
.btn {
  @extend .btn-setup !important;
}

.btn-setup {
  background: red;
}
```

Result

```
.btn {
  background: red !important;
}

.btn-setup {
  background: red;
}
```

**Comment by minimit** [comment]
@jonathantneal i've seen you need to do a rewrite of the plugin. Will it come? or maybe you want to port the @extend rule to postcss-preset-env? Thanks

**Comment by romainmenke** [comment]
hi @minimit,

This is beyond the scope of this plugin and against the core concept.

`@extend` as a feature is purely : "act as if element with class `.foo` also matches class `.bar`".

Modifying the declarations by making them important goes against the fundamentals of the feature.
