### ISSUE TITLE
v3.0.0 not documented in the changelog

### ISSUE THREAD

**Issue by alienlebarge** [csstools/postcss-extend-rule#9]
There's no information in `CHANGELOG.md` about v3.0.0

**Comment by jonathantneal** [comment]
I need a lot of help with v3. It was a buggy upgrade. I probably need time to do it over. I actually need this plugin, and have not been able to use it. You know how weird that is? It’s weird.

**Comment by romainmenke** [comment]
I don't think this will ever happen :/
Too much time has passed.

We will do our best to document future changes better.
